apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: maven
    image: jrmcdonald/jenkins-maven-agent:1.0.7
    imagePullPolicy: Always
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      - name: MAVEN_OPTS
        value: '-Xmx1024m'
    command:
      - cat
    tty: true
    volumeMounts:
      - name: jenkins-mvn-settings
        mountPath: /root/.m2/settings.xml
        subPath: settings.xml
      - name: jenkins-mvn-settings
        mountPath: /root/.m2/settings-security.xml
        subPath: settings-security.xml
  - name: dind
    image: docker:18.09-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}
  - name: jenkins-mvn-settings
    secret:
      secretName: maven-settings